### PR TITLE
Ported to VS v1.18

### PR DESCRIPTION
**Pull request by fipil**
Hi!
you probably don't have time to port your great mod to vs1.18. So I did it. Would you be so kind as to check it and if it's ok, post StoneQuary for 1.18? Hope that I did it well :-).
Fipil.

### CODE REVIEW

**Comment by DArkHekRoMaNT** [comment]
It would be nice to ask about 1.18 first

The update has been ready for a long time, but I'm waiting for the multiblock API fix (I have reported this three times already since pre.8 )

anegostudios/VintageStory-Issues#2606

**Comment by DArkHekRoMaNT** [comment]
I updated the files and added the [pre.1](https://github.com/DArkHekRoMaNT/StoneQuarry/releases/tag/v3.0.0-pre.1) version of SQ , but it has problems with buggy interaction with slabs

**Comment by fipil** [comment]
Aha, okay. I read your comment that it's coming soon, but was looking at the source code on github and didn't see any activity there for a long time. So I thought that you promised it, but you're so busy that you hadn't time to do it, since promised.
I'm sorry for my misunderstonding. I'm looking forward to the update, it's great mod! :-)

**Comment by fipil** [comment]
Maybe put an explanation comment to the mod page explaining why it's waiting to upgrade, so no anyone else is confused as me?

**Pull request closed without merging**
